services:
  - type: web
    name: bot-raposa-cacadora
    CHANNEL_USERNAME: @raposacacadora
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: BOT_TOKEN
        sync: false
